# Generated by Django 5.1.3 on 2025-04-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidencia',
            old_name='creado_por',
            new_name='creada_por',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='dispositivo',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='prioridad',
        ),
        migrations.AddField(
            model_name='incidencia',
            name='vista_por_admin',
            field=models.BooleanField(default=False),
        ),
    ]
