# Generated by Django 5.1.3 on 2025-05-01 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_rename_creado_por_incidencia_creada_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='titulo',
        ),
        migrations.AddField(
            model_name='incidencia',
            name='centro',
            field=models.CharField(choices=[('CENTRAL', 'CENTRAL'), ('CPM I', 'CPM I'), ('CPM II', 'CPM II'), ('RGA III', 'RGA III'), ('CPM IV', 'CPM IV'), ('DISL V', 'DISL V'), ('CPM VII', 'CPM VII'), ('CPM X', 'CPM X'), ('ISL XI', 'ISL XI'), ('ISL XII', 'ISL XII'), ('ISL XIII', 'ISL XIII'), ('CAL XIV', 'CAL XIV'), ('CPM XV', 'CPM XV')], default='CENTRAL', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidencia',
            name='fecha',
            field=models.DateField(default=datetime.date(2025, 5, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidencia',
            name='prioridad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Media', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidencia',
            name='relativa',
            field=models.CharField(choices=[('1', 'Línea y/o dispositivo telefónico corporativo'), ('2', 'Ordenador'), ('3', 'Internet'), ('4', 'Cuenta Corporativa GSuite'), ('5', 'Impresora'), ('6', 'Plataforma gestion.grupoanide.es'), ('7', 'Dispositivos personales autorizados'), ('8', 'Control de accesos'), ('9', 'Otro')], default='1', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidencia',
            name='urgencia',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
