# Generated by Django 5.1.3 on 2025-05-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0003_remove_incidencia_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='centro_anide',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='contacto_dispositivo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='cuenta_dispositivo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='cuenta_gsuite',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='eliminar_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='eliminar_nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='eliminar_urgente',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='fecha_inicio_incidencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='imei',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='imei_personal',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='intervencion_solicitada',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='modelo_personal',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='motivo_intervencion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='numero_serie',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='otorgar_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='otorgar_nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='otorgar_urgente',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='puesto_trabajo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='sesion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='telefono_contacto',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='tipo_incidencia_gsuite',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='tipo_incidencia_impresora',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='tipo_incidencia_internet',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='tipo_incidencia_ordenador',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='tipo_incidencia_plataforma',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='tipo_incidencia_telefono',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='tipo_solicitud_dispositivo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='trabajador_dispositivo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='trabajador_plataforma',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='centro',
            field=models.CharField(choices=[('CENTRAL', 'CENTRAL'), ('CPM I', 'CPM I'), ('CPM II', 'CPM II'), ('RGA III', 'RGA III'), ('CPM IV', 'CPM IV'), ('DISL V', 'DISL V'), ('CPM VII', 'CPM VII'), ('CPM X', 'CPM X'), ('ISL XI', 'ISL XI'), ('ISL XII', 'ISL XII'), ('ISL XIII', 'ISL XIII'), ('CAL XIV', 'CAL XIV'), ('CPM XV', 'CPM XV')], default='CENTRAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='fecha',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='prioridad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Media', max_length=10),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='relativa',
            field=models.CharField(choices=[('1', 'Línea y/o dispositivo telefónico corporativo'), ('2', 'Ordenador'), ('3', 'Internet'), ('4', 'Cuenta Corporativa GSuite'), ('5', 'Impresora'), ('6', 'Plataforma gestion.grupoanide.es'), ('7', 'Dispositivos personales autorizados'), ('8', 'Control de accesos'), ('9', 'Otro')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='urgencia',
            field=models.BooleanField(default=False),
        ),
    ]
