# Generated by Django 5.1.3 on 2025-05-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0004_incidencia_centro_anide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('nueva', 'Nueva'), ('en_curso', 'En curso'), ('cerrada', 'Cerrada')], default='nueva', max_length=20),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
    ]
