# Generated by Django 5.1.3 on 2025-06-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0005_incidencia_estado_incidencia_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='centro',
            field=models.CharField(choices=[('CENTRAL', 'CENTRAL'), ('CPM I', 'CPM I'), ('CPM II', 'CPM II'), ('RGA III', 'RGA III'), ('CPM IV', 'CPM IV'), ('OISL V', 'OISL V'), ('CPM VII', 'CPM VII'), ('CPM X', 'CPM X'), ('ISL XI', 'ISL XI'), ('ISL XII', 'ISL XII'), ('ISL XIII', 'ISL XIII'), ('CAI XIV', 'CAI XIV'), ('CPM XV', 'CPM XV')], default='CENTRAL', max_length=50),
        ),
    ]
