# Generated by Django 5.1.3 on 2025-06-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0006_alter_incidencia_centro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ordenador', 'Ordenador'), ('telefono', 'Teléfono'), ('impresora', 'Impresora'), ('equipo_red', 'Equipo de Red')], max_length=20)),
                ('centro', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('comentarios', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.CharField(blank=True, max_length=100)),
                ('tipo_equipo', models.CharField(blank=True, max_length=100)),
                ('sistema_operativo', models.CharField(blank=True, max_length=100)),
                ('cuenta_usuario', models.TextField(blank=True)),
                ('clave', models.TextField(blank=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('garantia', models.DateField(blank=True, null=True)),
                ('descripcion_estado', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('linea', models.CharField(blank=True, max_length=100)),
                ('puesto', models.CharField(blank=True, max_length=100)),
                ('imei', models.CharField(blank=True, max_length=100)),
                ('desbloqueo', models.CharField(blank=True, max_length=100)),
                ('datos_sim', models.CharField(blank=True, max_length=100)),
                ('pin', models.CharField(blank=True, max_length=100)),
                ('puk1', models.CharField(blank=True, max_length=100)),
                ('puk2', models.CharField(blank=True, max_length=100)),
                ('ext_vpn', models.CharField(blank=True, max_length=100)),
                ('fijo', models.CharField(blank=True, max_length=100)),
                ('tarifa', models.CharField(blank=True, max_length=100)),
                ('restriccion', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono_direccion', models.CharField(blank=True, max_length=100)),
                ('ipv4', models.CharField(blank=True, max_length=100)),
                ('proveedor', models.CharField(blank=True, max_length=100)),
                ('nombre_equipo', models.CharField(blank=True, max_length=100)),
                ('detalles_conexion', models.TextField(blank=True)),
                ('ip_publica_fija', models.CharField(blank=True, max_length=100)),
                ('linea_movil', models.CharField(blank=True, max_length=100)),
                ('linea_sim', models.CharField(blank=True, max_length=100)),
                ('linea_pin', models.CharField(blank=True, max_length=100)),
                ('linea_puk', models.CharField(blank=True, max_length=100)),
                ('tarifa_sin_iva', models.CharField(blank=True, max_length=100)),
                ('terminal_imei', models.CharField(blank=True, max_length=100)),
                ('terminal_num_serie', models.CharField(blank=True, max_length=100)),
                ('wifi_clave', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Dispositivo',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
